# Generated by Django 5.2.6 on 2025-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('watched', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
    ]
